"""Capability-based enforcement for code generated by authoring nodes."""

from __future__ import annotations

import ast
from dataclasses import dataclass, field
from typing import Any

from robomex.core.events import emit_event
from robomex.core.sandbox.action_block import (
    ActionBlockStatus,
    BlockExecutionResult,
    SemanticActionBlock,
)


PERCEPTION_READ = "perception_read"
ARTIFACT_WRITE = "artifact_write"
GEOMETRY_COMPUTE = "geometry_compute"
SIMULATION_PROBE = "simulation_probe"
ACTIVE_PERCEPTION = "active_perception"
ROBOT_MOTION = "robot_motion"
OBJECT_MANIPULATION = "object_manipulation"
GRIPPER_CONTROL = "gripper_control"

KNOWN_CAPABILITIES = frozenset(
    {
        PERCEPTION_READ,
        ARTIFACT_WRITE,
        GEOMETRY_COMPUTE,
        SIMULATION_PROBE,
        ACTIVE_PERCEPTION,
        ROBOT_MOTION,
        OBJECT_MANIPULATION,
        GRIPPER_CONTROL,
    }
)

# The registry is intentionally centralized.  Prompts describe capabilities, but
# this table is the enforcement source of truth.
CALL_EFFECTS: dict[str, str] = {
    "get_observation": PERCEPTION_READ,
    "query_vlm": PERCEPTION_READ,
    "segment_sam3_text_prompt": PERCEPTION_READ,
    "segment_sam3_point_prompt": PERCEPTION_READ,
    "segment_sam3_box_prompt": PERCEPTION_READ,
    "vlm_bbox_detection": PERCEPTION_READ,
    "vlm_point_detection": PERCEPTION_READ,
    "mask_to_world_points": GEOMETRY_COMPUTE,
    "pixel_to_world_point": GEOMETRY_COMPUTE,
    "depth_to_point_cloud": GEOMETRY_COMPUTE,
    "decompose_transform": GEOMETRY_COMPUTE,
    "rotation_matrix_to_quaternion": GEOMETRY_COMPUTE,
    "transform_points": GEOMETRY_COMPUTE,
    "normalize_vector": GEOMETRY_COMPUTE,
    "subsample_point_cloud": GEOMETRY_COMPUTE,
    "filter_noise": GEOMETRY_COMPUTE,
    "get_oriented_bounding_box_from_3d_points": GEOMETRY_COMPUTE,
    "plan_grasp": GEOMETRY_COMPUTE,
    "plan_grasp_from_point_clouds": GEOMETRY_COMPUTE,
    "parse_grasp_poses_for_curobo": GEOMETRY_COMPUTE,
    "create_curobo_world_from_depth": GEOMETRY_COMPUTE,
    "create_curobo_world_from_pointcloud": GEOMETRY_COMPUTE,
    "create_curobo_world_from_observation": GEOMETRY_COMPUTE,
    "update_curobo_world": GEOMETRY_COMPUTE,
    "update_curobo_world_with_object": GEOMETRY_COMPUTE,
    "plan_grasp_trajectory": GEOMETRY_COMPUTE,
    "plan_with_grasped_object": GEOMETRY_COMPUTE,
    "solve_ik": GEOMETRY_COMPUTE,
    "numpy.save": ARTIFACT_WRITE,
    "np.save": ARTIFACT_WRITE,
    "numpy.savez": ARTIFACT_WRITE,
    "np.savez": ARTIFACT_WRITE,
    "Path.write_text": ARTIFACT_WRITE,
    "Path.write_bytes": ARTIFACT_WRITE,
    "pathlib.Path.write_text": ARTIFACT_WRITE,
    "pathlib.Path.write_bytes": ARTIFACT_WRITE,
    "os.remove": ARTIFACT_WRITE,
    "os.unlink": ARTIFACT_WRITE,
    "os.rename": ARTIFACT_WRITE,
    "os.replace": ARTIFACT_WRITE,
    "shutil.rmtree": ARTIFACT_WRITE,
    "Path.unlink": ARTIFACT_WRITE,
    "Path.rename": ARTIFACT_WRITE,
    "pathlib.Path.unlink": ARTIFACT_WRITE,
    "pathlib.Path.rename": ARTIFACT_WRITE,
    "open": ARTIFACT_WRITE,
    "write": ARTIFACT_WRITE,
    "save": ARTIFACT_WRITE,
    "save_rgb": ARTIFACT_WRITE,
    "goto_home_joint_position": ACTIVE_PERCEPTION,
    "goto_pose": ROBOT_MOTION,
    "move_to_joints": ROBOT_MOTION,
    "execute_joint_trajectory": ROBOT_MOTION,
    "open_gripper": GRIPPER_CONTROL,
    "close_gripper": GRIPPER_CONTROL,
    "reset": OBJECT_MANIPULATION,
    "step": OBJECT_MANIPULATION,
}

# Hard-denied regardless of policy: process escapes and dynamic code execution,
# which would blind the AST scan below. Pure in-process introspection builtins
# (getattr/setattr/vars/dir/...) are deliberately NOT listed — the enforcement
# boundary is the capability-tagged env API namespace, not the Python language
# (M1.5 Fix B; mirrors opencode gating tool boundaries, never language builtins).
DYNAMIC_OR_PROCESS_CALLS = frozenset(
    {
        "eval",
        "exec",
        "compile",
        "__import__",
        "subprocess.run",
        "subprocess.call",
        "subprocess.Popen",
        "os.system",
        "os.popen",
    }
)

# Introspection and plain data-shaping builtins are never a capability boundary,
# even under ``unknown_calls="deny"``: blocking them cannot stop hostile code and
# only taxes honest agents into wasted repair turns.
SAFE_BUILTINS = frozenset(
    {
        "getattr",
        "setattr",
        "delattr",
        "hasattr",
        "vars",
        "dir",
        "type",
        "isinstance",
        "issubclass",
        "repr",
        "str",
        "int",
        "float",
        "bool",
        "len",
        "list",
        "tuple",
        "dict",
        "set",
        "sorted",
        "enumerate",
        "zip",
        "range",
        "min",
        "max",
        "sum",
        "abs",
        "round",
        "print",
        "format",
    }
)


@dataclass(frozen=True)
class CapabilityPolicy:
    allowed: frozenset[str] = field(default_factory=frozenset)
    unknown_calls: str = "allow"

    def __post_init__(self) -> None:
        unknown = set(self.allowed) - KNOWN_CAPABILITIES
        if unknown:
            raise ValueError(f"Unknown capability name(s): {', '.join(sorted(unknown))}")
        if self.unknown_calls not in {"allow", "deny"}:
            raise ValueError("unknown_calls must be 'allow' or 'deny'.")

    def violations(self, code: str) -> tuple[tuple[str, str], ...]:
        try:
            calls = called_function_names(code)
        except SyntaxError:
            return (("<syntax>", "invalid_syntax"),)
        violations: list[tuple[str, str]] = []
        for call in calls:
            effect = _call_effect(call)
            if effect is None:
                if call in SAFE_BUILTINS:
                    continue
                if call in DYNAMIC_OR_PROCESS_CALLS or self.unknown_calls == "deny":
                    violations.append((call, "unknown"))
                continue
            if effect not in self.allowed:
                violations.append((call, effect))
        return tuple(violations)


def effective_capabilities(
    requested: frozenset[str],
    ceiling: frozenset[str],
) -> frozenset[str]:
    """Intersect a contracted specialist grant with the global runtime ceiling."""

    unknown = requested - KNOWN_CAPABILITIES
    if unknown:
        raise ValueError(f"Unknown capability name(s): {', '.join(sorted(unknown))}")
    denied = requested - ceiling
    if denied:
        raise PermissionError(
            f"Capability request exceeds configured ceiling: {', '.join(sorted(denied))}."
        )
    return requested


class CapabilityBoundBlockExecutor:
    """Apply a node's capability policy before delegating to the sandbox."""

    def __init__(self, inner: Any, policy: CapabilityPolicy, *, node_id: str = "") -> None:
        self.inner = inner
        self.policy = policy
        self.node_id = node_id

    @property
    def env(self) -> Any:
        return getattr(self.inner, "env", None)

    def run_block(self, block: SemanticActionBlock) -> BlockExecutionResult:
        # Runtime-authored setup blocks (e.g. skill sys.path wiring, M1.5 Fix C)
        # are not agent code; the runtime does not police itself.
        if block.metadata.get("runtime_setup"):
            return self.inner.run_block(block)
        violations = self.policy.violations(block.code)
        if not violations:
            return self.inner.run_block(block)
        reason = render_denial_message(violations, self.policy)
        emit_event(
            "capability_denied",
            reason,
            node_id=self.node_id,
            violations=[{"call": name, "effect": effect} for name, effect in violations],
        )
        return BlockExecutionResult(
            block=block,
            ok=False,
            status=ActionBlockStatus.SKIPPED,
            stdout="",
            stderr=reason,
            info={
                "blocked_calls": [name for name, _ in violations],
                "capability_violations": [
                    {"call": name, "effect": effect} for name, effect in violations
                ],
                "authoring_node": self.node_id,
            },
        )


def apis_for_capabilities(allowed: frozenset[str]) -> tuple[str, ...]:
    """The env API names a capability grant actually unlocks (for repair hints)."""

    return tuple(
        sorted(name for name, effect in CALL_EFFECTS.items() if effect in allowed)
    )


def render_denial_message(
    violations: tuple[tuple[str, str], ...],
    policy: CapabilityPolicy,
) -> str:
    """A denial written for LLM repair: what was rejected, why, and which lever fixes it."""

    parts: list[str] = []
    for name, effect in violations:
        if effect == "unknown":
            parts.append(
                f"`{name}` is denied for every node: it spawns a process or executes "
                "dynamic code, which this sandbox never allows"
            )
        else:
            parts.append(
                f"`{name}` needs capability `{effect}`, which this node was not granted"
            )
    granted = ", ".join(sorted(policy.allowed)) or "(none)"
    usable = ", ".join(apis_for_capabilities(policy.allowed)) or "(none)"
    return (
        "Capability policy rejected this block: "
        + "; ".join(parts)
        + f". This node's granted capabilities: {granted}. "
        + f"Env APIs you may call: {usable}. "
        + "Plain Python (numpy, dict/list work, introspection, file reads) is always "
        + "allowed; rewrite the block using the APIs above or hand the missing step "
        + "to the node that owns it."
    )


def called_function_names(code: str) -> tuple[str, ...]:
    tree = ast.parse(code)
    names: set[str] = set()
    local_functions = {
        node.name
        for node in ast.walk(tree)
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    }
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        if isinstance(node.func, ast.Name):
            names.add(node.func.id)
        elif isinstance(node.func, ast.Attribute):
            names.add(_qualified_name(node.func))
    return tuple(sorted(names - local_functions))


def _qualified_name(node: ast.expr) -> str:
    parts: list[str] = []
    current = node
    while isinstance(current, ast.Attribute):
        parts.append(current.attr)
        current = current.value
    if isinstance(current, ast.Name):
        parts.append(current.id)
    else:
        return parts[0] if parts else "<dynamic>"
    return ".".join(reversed(parts))


def _call_effect(call: str) -> str | None:
    exact = CALL_EFFECTS.get(call)
    if exact is not None:
        return exact
    # Runtime APIs may be exposed directly or through an env/api namespace.
    return CALL_EFFECTS.get(call.rsplit(".", 1)[-1])
