"""Episode-level orchestration contracts for RoboMEx v2."""

from robomex.orchestration.arena_coding_provider import (
    ArenaCodingAgentProvider,
    ArenaCodingBridgeContractError,
    ArenaCodingBridgeError,
    ArenaCodingWorkerRuntime,
    MotionPreviewFrame,
    MotionPreviewRenderer,
    MotionPreviewResult,
)
from robomex.orchestration.bowl_provider import (
    BOWL_PLACE_DETERMINISTIC_RUNNERS,
    BowlPlaceActorBindings,
    BowlPlaceActorProvider,
    BowlPlaceCodingBindings,
    BowlPlaceProviderConfig,
    BowlPlaceProviderError,
    BowlTrackingMode,
    SynchronizedBowlTrackSampler,
    SynchronizedTrackPair,
    build_bowl_place_actor_bindings,
    build_bowl_place_coding_profiles,
)
from robomex.orchestration.coding_provider import (
    DEFAULT_CODING_CAPABILITY_GRANTS,
    PROPOSAL_CAPABILITIES,
    CodingInvocationAudit,
    CodingProviderContractError,
    CodingProviderError,
    CodingWorkerRuntime,
    SkillCodingAgentProvider,
)
from robomex.orchestration.intent import (
    BudgetHint,
    EntityRef,
    IntentOutcome,
    IntentStatus,
    SubgoalIntent,
)
from robomex.orchestration.run_budget import (
    RunBudgetAuthority,
    RunBudgetError,
    RunBudgetExceededError,
    RunBudgetIdentityConflictError,
    RunBudgetIntegrityError,
    RunBudgetOperationStateError,
    RunBudgetOperationStatus,
    RunBudgetReservation,
    RunBudgetSnapshot,
    RunBudgetVector,
)
from robomex.orchestration.task_orchestrator import (
    AvailableArtifact,
    BoundedIntentPlanner,
    EpisodeOrchestrator,
    EpisodePlanningContext,
    EpisodeTaskResult,
    FixedIntentPlanner,
    IntentPlanner,
    PlannerCallBudget,
    PlannerCallLedger,
    PlannerDecision,
    PlannerDecisionKind,
    ReactivePlannerIntentAdapter,
    ScriptedIntentPlanner,
    ScriptedWorkflowAuthor,
    TaskRunState,
    TaskRunStatus,
    TaskStateLedger,
    WorkflowAuthor,
    WorkflowAuthoringContext,
    WorkflowBlueprint,
)

_LAZY_EXPORTS = {
    **dict.fromkeys(
        {
            "ManagerPolicyCallBudget",
            "ManagerResponseError",
            "ManagerWorkflowAuthor",
            "ManifestPinnedWorkflowAuthor",
            "PinnedBaselineManagerInvoker",
            "PolicyManagerInvoker",
            "RoboMExV2Agent",
            "TaskOrchestrationLimits",
            "V2AgentConfig",
            "V2ApplicationError",
        },
        "application",
    ),
    "InvocationUsage": "episode",
    "OutcomeAwareFixedIntentPlanner": "task_orchestrator",
    **dict.fromkeys(
        {
            "BowlApplicationAssemblyError",
            "BowlPlaceHandoff",
            "BowlPlaceHandoffError",
            "FeasibilityCheckerPin",
            "FixedBowlPlaceApplication",
            "FixedBowlPlaceApplicationConfig",
            "TrustedBowlApplicationExtensions",
            "build_bowl_skill_coding_provider",
            "build_fixed_bowl_place_application",
            "preflight_bowl_place_handoff",
        },
        "bowl_application",
    ),
    **dict.fromkeys(
        {
            "BowlArenaFactoryError",
            "BowlArenaPointCloudPreviewPin",
            "BowlArenaPreviewRuntimeProvenance",
            "BowlCorrectionArenaFactoryAssembly",
            "BowlCorrectionArenaFactoryConfig",
            "BowlCorrectionCandidateConfig",
            "BowlMotionPlanningPin",
            "build_bowl_correction_arena_factory",
        },
        "bowl_arena",
    ),
    **dict.fromkeys(
        {
            "BowlSwarmApplicationAssemblyError",
            "RiskAdaptiveBowlPlaceApplication",
            "RiskAdaptiveBowlPlaceApplicationConfig",
            "build_risk_adaptive_bowl_place_application",
        },
        "bowl_swarm_application",
    ),
    **dict.fromkeys(
        {
            "DeterministicMotionRiskProvider",
            "MotionRiskActorBindings",
            "MotionRiskProviderConfig",
            "build_motion_risk_actor_bindings",
        },
        "risk_provider",
    ),
}


def __getattr__(name: str):
    """Load the application facade lazily to avoid contracts/bootstrap cycles."""

    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    import importlib

    module = importlib.import_module(f"robomex.orchestration.{module_name}")
    return getattr(module, name)


__all__ = [
    "ArenaCodingAgentProvider",
    "ArenaCodingBridgeContractError",
    "ArenaCodingBridgeError",
    "ArenaCodingWorkerRuntime",
    "BudgetHint",
    "BOWL_PLACE_DETERMINISTIC_RUNNERS",
    "BowlTrackingMode",
    "BowlPlaceActorBindings",
    "BowlPlaceActorProvider",
    "BowlPlaceCodingBindings",
    "BowlPlaceProviderConfig",
    "BowlPlaceProviderError",
    "BowlApplicationAssemblyError",
    "BowlArenaFactoryError",
    "BowlArenaPointCloudPreviewPin",
    "BowlArenaPreviewRuntimeProvenance",
    "BowlCorrectionArenaFactoryAssembly",
    "BowlCorrectionArenaFactoryConfig",
    "BowlCorrectionCandidateConfig",
    "BowlMotionPlanningPin",
    "BowlPlaceHandoff",
    "BowlPlaceHandoffError",
    "BowlSwarmApplicationAssemblyError",
    "DeterministicMotionRiskProvider",
    "FeasibilityCheckerPin",
    "FixedBowlPlaceApplication",
    "FixedBowlPlaceApplicationConfig",
    "ManagerPolicyCallBudget",
    "ManagerResponseError",
    "ManagerWorkflowAuthor",
    "ManifestPinnedWorkflowAuthor",
    "MotionRiskActorBindings",
    "MotionRiskProviderConfig",
    "MotionPreviewFrame",
    "MotionPreviewRenderer",
    "MotionPreviewResult",
    "SynchronizedBowlTrackSampler",
    "SynchronizedTrackPair",
    "PolicyManagerInvoker",
    "RoboMExV2Agent",
    "TaskOrchestrationLimits",
    "V2AgentConfig",
    "V2ApplicationError",
    "AvailableArtifact",
    "BoundedIntentPlanner",
    "CodingInvocationAudit",
    "CodingProviderContractError",
    "CodingProviderError",
    "CodingWorkerRuntime",
    "DEFAULT_CODING_CAPABILITY_GRANTS",
    "EntityRef",
    "EpisodeOrchestrator",
    "EpisodePlanningContext",
    "EpisodeTaskResult",
    "FixedIntentPlanner",
    "IntentPlanner",
    "IntentOutcome",
    "IntentStatus",
    "PlannerDecision",
    "PlannerDecisionKind",
    "PlannerCallBudget",
    "PlannerCallLedger",
    "PinnedBaselineManagerInvoker",
    "PROPOSAL_CAPABILITIES",
    "ReactivePlannerIntentAdapter",
    "RiskAdaptiveBowlPlaceApplication",
    "RiskAdaptiveBowlPlaceApplicationConfig",
    "RunBudgetAuthority",
    "RunBudgetError",
    "RunBudgetExceededError",
    "RunBudgetIdentityConflictError",
    "RunBudgetIntegrityError",
    "RunBudgetOperationStateError",
    "RunBudgetOperationStatus",
    "RunBudgetReservation",
    "RunBudgetSnapshot",
    "RunBudgetVector",
    "ScriptedIntentPlanner",
    "ScriptedWorkflowAuthor",
    "SkillCodingAgentProvider",
    "SubgoalIntent",
    "TrustedBowlApplicationExtensions",
    "TaskRunState",
    "TaskRunStatus",
    "TaskStateLedger",
    "WorkflowAuthor",
    "WorkflowAuthoringContext",
    "WorkflowBlueprint",
    "build_bowl_place_actor_bindings",
    "build_bowl_correction_arena_factory",
    "build_bowl_place_coding_profiles",
    "build_bowl_skill_coding_provider",
    "build_fixed_bowl_place_application",
    "build_motion_risk_actor_bindings",
    "build_risk_adaptive_bowl_place_application",
    "InvocationUsage",
    "OutcomeAwareFixedIntentPlanner",
    "preflight_bowl_place_handoff",
]
